[package]
name = "plat-smt-web-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
plat-smt = {path = "..", features = ["interpolant"]}
wasm-bindgen = "0.2.91"

[profile.release]
lto = true
codegen-units = 1